# Generated by Django 4.2.1 on 2023-06-11 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('currency_code', models.CharField(choices=[('GBPUSD', 'GBPUSD'), ('EURAUD', 'EURAUD'), ('USDCAD', 'USDCAD')], default='USDCAD', max_length=10)),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interval_data', to='currency_chart_app.interval')),
            ],
        ),
    ]
