# Generated by Django 4.2.1 on 2023-06-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_chart_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencydata',
            name='currency_code',
            field=models.CharField(choices=[('GBPUSD', 'GBPUSD'), ('EURAUD', 'EURAUD'), ('USDCAD', 'USDCAD')], default='USDCAD', max_length=10),
        ),
    ]
